### ISSUE TITLE
RUN 

### ISSUE THREAD

**Issue by d14mittal** [Shubha2207/E-waste-Management-web#1]
how do I run the website, i.e. where is the main HTML page

**Comment by Shubha2207** [comment]
app.js is the main entry point.
Use command 'node app.js' to execute the file.

**Comment by akashkorke** [comment]
I have tried to run the file using command node app.js but it's showing error ' cannot find module'.. 
![Uploading IMG_20210723_134309.jpg…]()

**Comment by yashk9168** [comment]
i am beginner so can you plz tell me how to run the code after extracting it

**Comment by yashk9168** [comment]
i am beginner so can you plz tell me how to run the code after extracting it

**Comment by d14mittal** [comment]
Install node.js in your windows/mac system, it’s better if you choose the LTS version. 
then clone the project.
Open command prompt/terminal in directory where app.js is present.
Execute ‘node app.js’
It should say something like app is running on port number…then do localhost:<port-number> on your browser.
That should be it, I haven’t tried this project now, but this should be it.
