### ISSUE TITLE
images are not loading

### ISSUE THREAD

**Issue by muktikalsekar** [Shubha2207/E-waste-Management-web#2]

**Comment by Shubha2207** [comment]
This might be because of an incorrect file path.
The following article might help :
https://www.w3schools.com/html/html_filepaths.asp

**Comment by muktikalsekar** [comment]
yes.
thank you

**Comment by lbsupraja** [comment]
this file path where did kept

**Comment by lbsupraja** [comment]
can you please tell me how did rectify this issue
